### ISSUE TITLE
On referencing local files

### ISSUE THREAD

**Issue by smbadiwe** [7-Light/seeit.github.io#1]
https://github.com/7-Light/seeit.github.io/blob/6a2d8b4114f18e057df0cd57ae53a45e5ad96632/index.html#L24

The `house.jpg` file being referenced here exists on your local machine and nowhere else. That's why it's not displaying when you browse the site but will display when you browse the site locally on your computer.

Any local file you want included must be somewhere within the root folder holding the site contents, and then referenced using [relative path](https://www.codingtag.com/absolute-vs-relative-path-links-in-html).

You can simply copy the image into the folder and reference it like this:
```
<img  src="house.jpg" alt="Learning Zone">
```
or
```
<img  src="./house.jpg" alt="Learning Zone">
```

As you build bigger sites with more static files, you'll have to use a folder structure to organize the different file types. But don't worry about it for now.

**Comment by 7-Light** [comment]
Alright then. Thanks a bunch
